#!/use/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# pull される前後を比較し、package-lock.json の変更があれば npm ci を行う
(git diff @{1} HEAD --name-only | grep "package-lock.json" > /dev/null) && npm install || echo "No need npm install operation."
