#!/bin/sh

# mergeした差分ファイル取得
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

# 特定のファイルが差分に含まれていれば、コマンドを実行する関数
check_run() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# package-lock.jsonが差分に含まれていれば、npm installを実行する
check_run package-lock.json "npm install"
